### ISSUE TITLE
Latest posts on homepage

### ISSUE THREAD

**Issue by ioanrobciuc** [Codeinwp/constructzine-lite#37]
"As vrea sa facem update la temele lite care nu sunt publicate si sa punem pe homepage cumva latest posts .

Ideea e ca eu vreau sa afisam homepage custom by default, dar cum setarea default in wp este : Latest posts, trebuie sa o respectam.

Se pot face mici smecherii de genul : https://wordpress.org/themes/vantage, adica sa pune o mica sectiune cu latest posts undeva .

O sa fac eu asta la Zerif, si ar trebui facut si la Constructzine Lite + temele in asteptare ( medica/denta/mooveit /plumbeit )"

**Comment by ineagu** [comment]
Ar trebui sa terminam temele lite gen medica/denta/mooveit sunt probleme acolo cu text-domain, screenshoturi nu au dimensiune corecta etc.

**Comment by robi09** [comment]
Vrei sa le verific pe fiecare in parte sa vad exact ce probleme mai sunt?

**Comment by ineagu** [comment]
da, le poti verifica. apoi putem face lawyeria pro cu ce chestii am mai pus, dar cum am zis cu fork

**Comment by ineagu** [comment]
+ temele alea lite adaugate pe site, nu stiu daca sunt toate

**Comment by rodica-andronache** [comment]
@ineagu aici putem inchide nu?

**Comment by ineagu** [comment]
dap


On Thu, Apr 7, 2016 at 2:18 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> aici putem inchide nu?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/constructzine-lite/issues/37#issuecomment-206822148>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
