### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/constructzine-lite#49]
A couple of suggestions:
Improve the documentation regarding the slider - it took me a while to figure out how to add and remove slides
Improve the documentation regarding the [zee...] tags. I'm really new to Wordpress and I still don't really understand how to use those. For example I ended up using this to customize the services panel. I had to look up the category ID, it wasn't intuitive:
[zee_container class="medium-blue" id="services"] [zee_service category="21" column="3" number="3"][/zee_container]
There are some other documentation updates that could be made. But I understand that it is a free theme, and I am new to Wordpress so there is some learning on my end as well

**Comment by rodica-andronache** [comment]
@mariusghitulescu sigur se refera la constructzine lite aici? Ca nu-mi pare nimic cunoscut :D
